name: 🧠 Auto Generate Golang Facts

on:
  schedule:
    - cron: '0 2 * * *'  # setiap jam 2 pagi UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run AI Fact Generator
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_API_BASE_URL: ${{ secrets.AI_API_BASE_URL }}
        run: |
          go run ai-fact-bot.go

      - name: Check current git remote 
        run: git remote -v

      - name: Commit & push if README changed
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "ak4bento"
          git config --global user.email "akil.dcc@gmail.com"
          git add .
          git commit -m "🤖 update AI fact"
          git push https://ak4bento:${TOKEN}@github.com/ak4bento/ai-fact-bot.git HEAD:main
