name: 🧠 Auto Generate Golang Facts

on:
  schedule:
    - cron: '0 2 * * *'  # setiap jam 2 pagi UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run AI Fact Generator
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_API_BASE_URL: ${{ secrets.AI_API_BASE_URL }}
        run: |
          go run ai-fact-bot.go

      - name: Set remote with GH_PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://ak4bento:${GH_PAT}@github.com/ak4bento/ai-fact-bot.git
      
      - name: Check current git remote 
        run: git remote -v

      - name: Commit & push 
        run: |
          git config --global user.name "ak4bento"
          git config --global user.email "akil.dcc@gmail.com"
          git add README.md || true
          git diff --cached --quiet || (
            git commit -m "🤖 update AI fact" &&
            git push origin HEAD:main
          )
