name: 🧠 Auto Generate Golang Facts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # setiap hari jam 09:00 WIB

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run script
        run: go run scripts/generate.go

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add thoughts.md
          git commit -m "🟢 auto commit: $(date)" || echo "nothing to commit"
          git push
