name: 🧠 Auto Generate Golang Facts

on:
  schedule:
    - cron: '0 2 * * *'  # setiap jam 2 pagi UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run AI Fact Generator
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_API_BASE_URL: ${{ secrets.AI_API_BASE_URL }}
        run: |
          go run ai-fact-bot.go

      - name: Commit & push if README changed
        run: |
          git config user.name "ak4bento"
          git config user.email "akil.dcc@gmail.com"
          git diff
          git add README.md || true
          git diff --cached --quiet || (git commit -m "🤖 update AI fact" && git push)
