name: Daily AI Fact

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-fact:
    runs-on: ubuntu-latest
    steps:
      - uses: ak4bento/ai-fact-bot@main
        with:
          api_key: ${{ secrets.AI_API_KEY }}
          api_base_url: "https://openrouter.ai/api/v1"

      - name: Commit & Push updated README
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md || true
          git diff --cached --quiet || (
            git commit -m \"🤖 update AI fact\" &&
            git push https://${{ github.actor }}:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
          )
